apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-udaconnect
  name: frontend-udaconnect
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    service: frontend-udaconnect
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend-udaconnect
  name: frontend-udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-udaconnect
  template:
    metadata:
      labels:
        service: frontend-udaconnect
    spec:
      containers:
        - image: dmukaliy/frontend-udaconnect:latest
          name: frontend-udaconnect
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "256m"
      restartPolicy: Always
